{
  "type": "record",
  "name": "ClickstreamEventAvro",
  "namespace": "com.myntra.sense.telemetry.avro",
  "doc": "Avro schema for UI Clickstream Events ingested into Kafka topic: clickstream_events",
  "fields": [
    { "name": "event_id", "type": "string" },
    { "name": "user_id", "type": "string" },
    { "name": "session_id", "type": "string" },
    { "name": "device_id", "type": "string" },
    { "name": "platform", "type": "string" },
    { "name": "screen_name", "type": "string" },
    { "name": "element_type", "type": "string" },
    { "name": "interaction_type", "type": "string" },
    { "name": "associated_product_id", "type": ["null", "string"], "default": null },
    { "name": "payload_metadata_json", "type": ["null", "string"], "default": null },
    { "name": "viewport_position_index", "type": "int", "default": 0 },
    { "name": "interaction_duration_ms", "type": "long", "default": 0 },
    { "name": "event_timestamp_ms", "type": "long" }
  ]
}
